# Generated by Django 6.0.4 on 2026-04-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="imagem",
            field=models.ImageField(upload_to="media/cursos/"),
        ),
    ]
