# Generated by Django 6.0.4 on 2026-04-11 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_code", models.IntegerField()),
                ("employee_code", models.IntegerField()),
                ("nome", models.CharField(max_length=100)),
                ("degree", models.CharField(blank=True, max_length=25, null=True)),
                ("regime", models.CharField(max_length=25)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=100)),
                ("data", models.DateField()),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("justificacao", models.TextField(blank=True)),
                ("alteracao", models.TextField(blank=True)),
                ("llm", models.CharField(blank=True, max_length=500)),
                ("fotos", models.ImageField(blank=True, upload_to="fotos_makingof/")),
            ],
        ),
        migrations.CreateModel(
            name="Tfc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("licenciatura", models.CharField(max_length=100)),
                ("aluno", models.CharField(max_length=100)),
                ("orientador", models.CharField(max_length=100)),
                ("area", models.CharField(max_length=100)),
                ("tecnologias", models.CharField(max_length=100)),
                ("palavras_chave", models.CharField(max_length=100)),
                ("rating", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("pdf", models.URLField()),
                ("resumo", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("classificacao", models.IntegerField()),
                ("descricao", models.TextField()),
                ("logo", models.ImageField(blank=True, upload_to="fotos_tecnologia/")),
                ("site_oficial", models.URLField(blank=True)),
                (
                    "formacao",
                    models.ManyToManyField(
                        blank=True, related_name="tecnologias", to="portfolio.formacao"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("conceitos", models.CharField(max_length=500)),
                ("descricao", models.TextField()),
                ("repositorio", models.CharField(blank=True, max_length=100)),
                (
                    "competencia",
                    models.ManyToManyField(
                        related_name="projetos", to="portfolio.competencia"
                    ),
                ),
                (
                    "tecnologia",
                    models.ManyToManyField(
                        related_name="projetos", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ano", models.IntegerField()),
                ("semestre", models.CharField(max_length=20)),
                ("ects", models.IntegerField()),
                ("objetivo", models.TextField(blank=True)),
                ("descricao", models.TextField(blank=True)),
                ("programa", models.TextField(blank=True)),
                ("imagem", models.ImageField(blank=True, upload_to="fotos_uc/")),
                (
                    "docente",
                    models.ManyToManyField(
                        blank=True, related_name="ucs", to="portfolio.docente"
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ucs",
                        to="portfolio.projeto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("curso_codigo", models.IntegerField()),
                ("nome", models.CharField(max_length=100)),
                ("semestres", models.IntegerField()),
                ("curso_ects", models.IntegerField()),
                ("descricao", models.TextField(blank=True)),
                ("objetivos", models.TextField(blank=True)),
                (
                    "uc",
                    models.ManyToManyField(
                        blank=True, related_name="licenciaturas", to="portfolio.uc"
                    ),
                ),
            ],
        ),
    ]
