# Generated by Django 6.0.4 on 2026-04-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tecnologia",
            name="site_oficial",
        ),
    ]
