# Generated by Django 6.0.4 on 2026-04-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_remove_tecnologia_site_oficial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="competencia",
            field=models.ManyToManyField(
                blank=True, related_name="projetos", to="portfolio.competencia"
            ),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="tecnologia",
            field=models.ManyToManyField(
                blank=True, related_name="projetos", to="portfolio.tecnologia"
            ),
        ),
    ]
