# Generated by Django 6.0.4 on 2026-04-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_projeto_competencia_alter_projeto_tecnologia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="makingof",
            name="fotos",
            field=models.ImageField(blank=True, upload_to="makingof_fotos/"),
        ),
    ]
