# Generated by Django 6.0.5 on 2026-05-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_makingof_fotos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="pdf",
            field=models.URLField(max_length=500),
        ),
    ]
