# Generated by Django 6.0.5 on 2026-05-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_alter_tfc_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="aluno",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="area",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="email",
            field=models.EmailField(max_length=500),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="licenciatura",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="orientador",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="palavras_chave",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="tecnologias",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="titulo",
            field=models.CharField(max_length=500),
        ),
    ]
