# Generated by Django 6.0.5 on 2026-05-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_alter_tfc_aluno_alter_tfc_area_alter_tfc_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="aluno",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="area",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="email",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="licenciatura",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="orientador",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="palavras_chave",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="pdf",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="tecnologias",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="titulo",
            field=models.TextField(),
        ),
    ]
